services:
  - type: web
    name: surveypro-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5041
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: JWT_REFRESH_SECRET
        sync: false
      - key: FRONTEND_URL
        value: https://surveyflow.vercel.app,http://localhost:3000
      - key: API_URL
        value: https://surveypro-ir3u.onrender.com